spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto:
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace